
<?php
     include 'testData.php';
    $jsonArr = array(
            'printDate' => $header['print_date'],
            'poNum' => $header['po_number'],
            'material' => $header['material'],
            'lineItem' => $header['line_item'],
            'job' => $header['job'],
            'partNum' => $header['part_no'],
            'dieID' => $header['die_id'],
            'mill' => $header['mill'],
            'stripWidth' => $header['strip_width'],
            'gage' => $header['gage'],
            'thickness' => $header['thickness'],
            'pattern' => $header['pattern'],
            'millSpec' => $header['mill_spec'],
            'fractionsHole' => $records['fractions_hole'],
            'fractionsCenter' => $header['fractions_center'],
            'angle' => $header['angle'],
            'millAmps' => $header['mill_amps'],
            'millVolts' => $header['mill_volts'],
            'millSpeed' => $header['mill_speed'],
            'milltorchHeight' => $header['mill_torch_height'],
            'archLength' => $header['Arc_length'],
            'torchAngle' => $header['torch_angle'],
            'od' => $header['od'],
            'odPos' => $header['od_postive'],
            'odNeg' => $header['od_negtive'],
            'repairSpec' => $header['repair_spec'],
            'idDrift' => $header['id_drift'],
            'amps' => $header['repair_amps'],
            'volts' => $header['repair_volts'],
            'speed' => $header['repair_speed'],
            'fillerRod' => $header['filler_rod'],
            'repairTorchHeight' => $header['repair_torch_height'],
            'electroLength' => $header['electro_length'],
            'gasRepair' => $header['gas_repair'],
            'dimpleDepth' => $header['depth_of_dimple'],
            'dimpleDepthM' => $header['id_depth_of_dimple_minus'],
            'notes' => $header['notes'],
            'tubmilSetup' => $footer['tubmil_setup'],
            'tubmilSetup2' => $footer['tubmil_setup-2'],
            'tubmilSetup3' => $footer['tubmil_setup-3'],
            'tubmilSetup4' => $footer['tubmil_setup-4'],
    );

    
?>